# Generated by Django 5.1.4 on 2025-01-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0002_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
